version: '3'

services:
  api:
    build:
      context: ./api
    depends_on:
      - elasticsearch
    volumes: 
      ./api:/code
      # the destination path is fixed and should not be changed!
      - ./data/isrc_lookupn.csv:/data/isrc_lookup.csv
    ports: 
      - 5000:5000

  frontend:
    build:
      context: ./frontend
    ports:
      - 8080:8080

  elasticsearch:
    build:
      context: ./elasticsearch
    environment:
      # By default, the heap size of the elasticsearch container is 2gb, which is
      # also the default for Docker for Mac, leading it to crash if we don't use less.
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - 9200:9200

